
# This file is automatically generated, you probably don't want to edit this

mdsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mdsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            mdeMDS = "Sym",
            varSym = NULL,
            nmeSym = NULL,
            lvlSym = "ordinal",
            dimSym = 2,
            xfmSym = "none",
            xfiSym = 0,
            varRaw = NULL,
            nmeRaw = NULL,
            lvlRaw = "ordinal",
            dimRaw = 2,
            dirRaw = "col",
            xfmRaw = "none",
            varInd = NULL,
            nmeInd = NULL,
            lvlInd = "ordinal",
            dimInd = 2,
            xfmInd = "none",
            xfiInd = 0,
            clmSPP = FALSE,
            figCfg = TRUE,
            cfgBbl = FALSE,
            cfgInX = FALSE,
            cfgInY = FALSE,
            figShp = FALSE,
            figStr = FALSE,
            figRes = FALSE,
            figHst = FALSE,
            figWgh = FALSE, ...) {

            super$initialize(
                package="jMDS",
                name="mds",
                requiresData=TRUE,
                ...)

            private$..mdeMDS <- jmvcore::OptionList$new(
                "mdeMDS",
                mdeMDS,
                options=list(
                    "Sym",
                    "Raw",
                    "Ind"),
                default="Sym")
            private$..varSym <- jmvcore::OptionVariables$new(
                "varSym",
                varSym,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..nmeSym <- jmvcore::OptionVariable$new(
                "nmeSym",
                nmeSym,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                rejectInf=FALSE)
            private$..lvlSym <- jmvcore::OptionList$new(
                "lvlSym",
                lvlSym,
                options=list(
                    "interval",
                    "ordinal"),
                default="ordinal")
            private$..dimSym <- jmvcore::OptionInteger$new(
                "dimSym",
                dimSym,
                min=2,
                max=10,
                default=2)
            private$..xfmSym <- jmvcore::OptionList$new(
                "xfmSym",
                xfmSym,
                options=list(
                    "none",
                    "corr",
                    "reverse",
                    "reciprocal",
                    "ranks",
                    "exp",
                    "Gaussian",
                    "cooccurrence",
                    "gravity",
                    "confusion",
                    "transition",
                    "membership",
                    "probability",
                    "integer"),
                default="none")
            private$..xfiSym <- jmvcore::OptionInteger$new(
                "xfiSym",
                xfiSym,
                default=0)
            private$..varRaw <- jmvcore::OptionVariables$new(
                "varRaw",
                varRaw,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..nmeRaw <- jmvcore::OptionVariable$new(
                "nmeRaw",
                nmeRaw,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor"),
                rejectInf=FALSE)
            private$..lvlRaw <- jmvcore::OptionList$new(
                "lvlRaw",
                lvlRaw,
                options=list(
                    "interval",
                    "ordinal"),
                default="ordinal")
            private$..dimRaw <- jmvcore::OptionInteger$new(
                "dimRaw",
                dimRaw,
                min=2,
                max=10,
                default=2)
            private$..dirRaw <- jmvcore::OptionList$new(
                "dirRaw",
                dirRaw,
                options=list(
                    "col",
                    "row"),
                default="col")
            private$..xfmRaw <- jmvcore::OptionList$new(
                "xfmRaw",
                xfmRaw,
                options=list(
                    "none",
                    "reverse",
                    "rank",
                    "pearson",
                    "kendall",
                    "spearman",
                    "minkowski_2",
                    "z_minkowski_2",
                    "minkowski_1",
                    "z_minkowski_1",
                    "minkowski_3",
                    "z_minkowski_3",
                    "minkowski_4",
                    "z_minkowski_4",
                    "binary",
                    "z_binary"),
                default="none")
            private$..varInd <- jmvcore::OptionVariables$new(
                "varInd",
                varInd,
                suggested=list(
                    "ordinal",
                    "continuous"),
                permitted=list(
                    "numeric"),
                rejectInf=FALSE)
            private$..nmeInd <- jmvcore::OptionVariable$new(
                "nmeInd",
                nmeInd,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "numeric"),
                rejectInf=FALSE)
            private$..lvlInd <- jmvcore::OptionList$new(
                "lvlInd",
                lvlInd,
                options=list(
                    "interval",
                    "ordinal"),
                default="ordinal")
            private$..dimInd <- jmvcore::OptionInteger$new(
                "dimInd",
                dimInd,
                min=2,
                max=10,
                default=2)
            private$..xfmInd <- jmvcore::OptionList$new(
                "xfmInd",
                xfmInd,
                options=list(
                    "none",
                    "corr",
                    "reverse",
                    "reciprocal",
                    "ranks",
                    "exp",
                    "Gaussian",
                    "cooccurrence",
                    "gravity",
                    "confusion",
                    "transition",
                    "membership",
                    "probability",
                    "integer"),
                default="none")
            private$..xfiInd <- jmvcore::OptionInteger$new(
                "xfiInd",
                xfiInd,
                default=0)
            private$..clmSPP <- jmvcore::OptionBool$new(
                "clmSPP",
                clmSPP,
                default=FALSE)
            private$..figCfg <- jmvcore::OptionBool$new(
                "figCfg",
                figCfg,
                default=TRUE)
            private$..cfgBbl <- jmvcore::OptionBool$new(
                "cfgBbl",
                cfgBbl,
                default=FALSE)
            private$..cfgInX <- jmvcore::OptionBool$new(
                "cfgInX",
                cfgInX,
                default=FALSE)
            private$..cfgInY <- jmvcore::OptionBool$new(
                "cfgInY",
                cfgInY,
                default=FALSE)
            private$..figShp <- jmvcore::OptionBool$new(
                "figShp",
                figShp,
                default=FALSE)
            private$..figStr <- jmvcore::OptionBool$new(
                "figStr",
                figStr,
                default=FALSE)
            private$..figRes <- jmvcore::OptionBool$new(
                "figRes",
                figRes,
                default=FALSE)
            private$..figHst <- jmvcore::OptionBool$new(
                "figHst",
                figHst,
                default=FALSE)
            private$..figWgh <- jmvcore::OptionBool$new(
                "figWgh",
                figWgh,
                default=FALSE)
            private$..ov_Cfg <- jmvcore::OptionOutput$new(
                "ov_Cfg")

            self$.addOption(private$..mdeMDS)
            self$.addOption(private$..varSym)
            self$.addOption(private$..nmeSym)
            self$.addOption(private$..lvlSym)
            self$.addOption(private$..dimSym)
            self$.addOption(private$..xfmSym)
            self$.addOption(private$..xfiSym)
            self$.addOption(private$..varRaw)
            self$.addOption(private$..nmeRaw)
            self$.addOption(private$..lvlRaw)
            self$.addOption(private$..dimRaw)
            self$.addOption(private$..dirRaw)
            self$.addOption(private$..xfmRaw)
            self$.addOption(private$..varInd)
            self$.addOption(private$..nmeInd)
            self$.addOption(private$..lvlInd)
            self$.addOption(private$..dimInd)
            self$.addOption(private$..xfmInd)
            self$.addOption(private$..xfiInd)
            self$.addOption(private$..clmSPP)
            self$.addOption(private$..figCfg)
            self$.addOption(private$..cfgBbl)
            self$.addOption(private$..cfgInX)
            self$.addOption(private$..cfgInY)
            self$.addOption(private$..figShp)
            self$.addOption(private$..figStr)
            self$.addOption(private$..figRes)
            self$.addOption(private$..figHst)
            self$.addOption(private$..figWgh)
            self$.addOption(private$..ov_Cfg)
        }),
    active = list(
        mdeMDS = function() private$..mdeMDS$value,
        varSym = function() private$..varSym$value,
        nmeSym = function() private$..nmeSym$value,
        lvlSym = function() private$..lvlSym$value,
        dimSym = function() private$..dimSym$value,
        xfmSym = function() private$..xfmSym$value,
        xfiSym = function() private$..xfiSym$value,
        varRaw = function() private$..varRaw$value,
        nmeRaw = function() private$..nmeRaw$value,
        lvlRaw = function() private$..lvlRaw$value,
        dimRaw = function() private$..dimRaw$value,
        dirRaw = function() private$..dirRaw$value,
        xfmRaw = function() private$..xfmRaw$value,
        varInd = function() private$..varInd$value,
        nmeInd = function() private$..nmeInd$value,
        lvlInd = function() private$..lvlInd$value,
        dimInd = function() private$..dimInd$value,
        xfmInd = function() private$..xfmInd$value,
        xfiInd = function() private$..xfiInd$value,
        clmSPP = function() private$..clmSPP$value,
        figCfg = function() private$..figCfg$value,
        cfgBbl = function() private$..cfgBbl$value,
        cfgInX = function() private$..cfgInX$value,
        cfgInY = function() private$..cfgInY$value,
        figShp = function() private$..figShp$value,
        figStr = function() private$..figStr$value,
        figRes = function() private$..figRes$value,
        figHst = function() private$..figHst$value,
        figWgh = function() private$..figWgh$value,
        ov_Cfg = function() private$..ov_Cfg$value),
    private = list(
        ..mdeMDS = NA,
        ..varSym = NA,
        ..nmeSym = NA,
        ..lvlSym = NA,
        ..dimSym = NA,
        ..xfmSym = NA,
        ..xfiSym = NA,
        ..varRaw = NA,
        ..nmeRaw = NA,
        ..lvlRaw = NA,
        ..dimRaw = NA,
        ..dirRaw = NA,
        ..xfmRaw = NA,
        ..varInd = NA,
        ..nmeInd = NA,
        ..lvlInd = NA,
        ..dimInd = NA,
        ..xfmInd = NA,
        ..xfiInd = NA,
        ..clmSPP = NA,
        ..figCfg = NA,
        ..cfgBbl = NA,
        ..cfgInX = NA,
        ..cfgInY = NA,
        ..figShp = NA,
        ..figStr = NA,
        ..figRes = NA,
        ..figHst = NA,
        ..figWgh = NA,
        ..ov_Cfg = NA)
)

mdsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mdsResults",
    inherit = jmvcore::Group,
    active = list(
        genInf = function() private$.items[["genInf"]],
        tblCfg = function() private$.items[["tblCfg"]],
        figCfg = function() private$.items[["figCfg"]],
        figShp = function() private$.items[["figShp"]],
        figStr = function() private$.items[["figStr"]],
        figRes = function() private$.items[["figRes"]],
        figHst = function() private$.items[["figHst"]],
        figWgh = function() private$.items[["figWgh"]],
        addInf = function() private$.items[["addInf"]],
        ov_Cfg = function() private$.items[["ov_Cfg"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Multidimensional Scaling")
            self$add(jmvcore::Html$new(
                options=options,
                name="genInf",
                clearWith=list(),
                content=""))
            self$add(jmvcore::Table$new(
                options=options,
                name="tblCfg",
                title="Configuration Table",
                refs=list(
                    "smacof_2009",
                    "smacof_2022",
                    "jMDS"),
                clearWith=list(
                    "mdeMDS",
                    "varSym",
                    "varRaw",
                    "varInd",
                    "xfmSym",
                    "xfmRaw",
                    "xfmInd",
                    "lvlSym",
                    "lvlRaw",
                    "lvlInd",
                    "dimSym",
                    "dimRaw",
                    "dimInd",
                    "dirRaw"),
                rows=0,
                columns=list(
                    list(
                        `name`="nmeObj", 
                        `title`="Objects", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="figCfg",
                title="Configuration Plot",
                width=450,
                height=400,
                renderFun=".pltCfg",
                visible="(figCfg)",
                clearWith=list(
                    "mdeMDS",
                    "varSym",
                    "varRaw",
                    "varInd",
                    "xfmSym",
                    "xfmRaw",
                    "xfmInd",
                    "lvlSym",
                    "lvlRaw",
                    "lvlInd",
                    "dimSym",
                    "dimRaw",
                    "dimInd",
                    "dirRaw")))
            self$add(jmvcore::Image$new(
                options=options,
                name="figShp",
                title="Shepard Diagram",
                width=450,
                height=400,
                renderFun=".pltShp",
                visible="(figShp)",
                clearWith=list(
                    "mdeMDS",
                    "varSym",
                    "varRaw",
                    "varInd",
                    "xfmSym",
                    "xfmRaw",
                    "xfmInd",
                    "lvlSym",
                    "lvlRaw",
                    "lvlInd",
                    "dimSym",
                    "dimRaw",
                    "dimInd",
                    "dirRaw")))
            self$add(jmvcore::Image$new(
                options=options,
                name="figStr",
                title="Stress Diagram",
                width=450,
                height=400,
                renderFun=".pltStr",
                visible="(figStr)",
                clearWith=list(
                    "mdeMDS",
                    "varSym",
                    "varRaw",
                    "varInd",
                    "xfmSym",
                    "xfmRaw",
                    "xfmInd",
                    "lvlSym",
                    "lvlRaw",
                    "lvlInd",
                    "dimSym",
                    "dimRaw",
                    "dimInd",
                    "dirRaw")))
            self$add(jmvcore::Image$new(
                options=options,
                name="figRes",
                title="Residual Diagram",
                width=450,
                height=400,
                renderFun=".pltRes",
                visible="(figRes)",
                clearWith=list(
                    "mdeMDS",
                    "varSym",
                    "varRaw",
                    "varInd",
                    "xfmSym",
                    "xfmRaw",
                    "xfmInd",
                    "lvlSym",
                    "lvlRaw",
                    "lvlInd",
                    "dimSym",
                    "dimRaw",
                    "dimInd",
                    "dirRaw")))
            self$add(jmvcore::Image$new(
                options=options,
                name="figHst",
                title="Histogram of the Dissimilarities",
                width=450,
                height=400,
                renderFun=".pltHst",
                visible="(figHst)",
                clearWith=list(
                    "mdeMDS",
                    "varSym",
                    "varRaw",
                    "varInd",
                    "xfmSym",
                    "xfmRaw",
                    "xfmInd",
                    "lvlSym",
                    "lvlRaw",
                    "lvlInd",
                    "dimSym",
                    "dimRaw",
                    "dimInd",
                    "dirRaw")))
            self$add(jmvcore::Image$new(
                options=options,
                name="figWgh",
                title="Weights Diagram",
                width=450,
                height=400,
                renderFun=".pltWgh",
                visible="(figWgh)",
                clearWith=list(
                    "mdeMDS",
                    "varInd",
                    "xfmInd",
                    "lvlInd",
                    "dimInd")))
            self$add(jmvcore::Html$new(
                options=options,
                name="addInf",
                clearWith=list(),
                content=""))
            self$add(jmvcore::Output$new(
                options=options,
                name="ov_Cfg",
                title="Configurations",
                varTitle="Configuration",
                varDescription="Configuration from MDS",
                measureType="continuous",
                clearWith=list(
                    "mdeMDS",
                    "varSym",
                    "varRaw",
                    "varInd",
                    "xfmSym",
                    "xfmRaw",
                    "xfmInd",
                    "lvlSym",
                    "lvlRaw",
                    "lvlInd",
                    "dimSym",
                    "dimRaw",
                    "dimInd")))}))

mdsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "mdsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "jMDS",
                name = "mds",
                version = c(1,0,0),
                options = options,
                results = mdsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = TRUE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Multidimensional Scaling
#'
#' Perform Multidimensional Scaling
#'
#' @examples
#' \donttest{
#' # TRIAL
#' # TRIAL
#' # TRIAL
#'}
#' @param data the data as a data frame
#' @param mdeMDS .
#' @param varSym a vector of strings naming the variables of interest in
#'   \code{data}
#' @param nmeSym a string with a variable name pointing to a column containing
#'   the variable names if \code{data} is a sparse matrix
#' @param lvlSym \code{'ordinal'} (default) or \code{'metric'}, the
#'   measurement level of the variables of interest
#' @param dimSym an integer (default: 2), number of MDS dimensions
#' @param xfmSym \code{'none'} (default), \code{'corr'}, \code{'reverse'},
#'   \code{'reciprocal'}, \code{'ranks'}, \code{'exp'}, \code{'Gaussian'},
#'   \code{'cooccurrence'}, \code{'gravity'}, \code{'confusion'},
#'   \code{'transition'}, \code{'membership'}, \code{'probability'}, or an
#'   integer value if \code{'none'}, the input data are already dissimilarities
#'   / distances; otherwise, which method to use for converting the original
#'   (similarity) matrix into a dissimiliarity / distance matrix that is then
#'   submitted to the MDS calculation
#' @param xfiSym an integer (default: 0) from which the original values are
#'   subtracted
#' @param varRaw a vector of strings naming the variables of interest in
#'   \code{data}
#' @param nmeRaw a string with a variable containg the names for the data in
#'   the rows (e.g., a participant ID)
#' @param lvlRaw \code{'ordinal'} (default) or \code{'metric'}, the
#'   measurement level of the variables of interest
#' @param dimRaw an integer (default: 2), number of MDS dimensions
#' @param dirRaw \code{'col'} (default) or \code{'row'}, are the distances
#'   analyzed between columns or rows
#' @param xfmRaw TBA
#' @param varInd a vector of strings naming the variables of interest in
#'   \code{data}
#' @param nmeInd a string with a variable name pointing to a column containing
#'   the variable names if \code{data} is composed of sparse matrices
#' @param lvlInd \code{'ordinal'} (default) or \code{'metric'}, the
#'   measurement level of the variables of interest
#' @param dimInd an integer (default: 2), number of MDS dimensions
#' @param xfmInd \code{'none'} (default), \code{'corr'}, \code{'reverse'},
#'   \code{'reciprocal'}, \code{'ranks'}, \code{'exp'}, \code{'Gaussian'},
#'   \code{'cooccurrence'}, \code{'gravity'}, \code{'confusion'},
#'   \code{'transition'}, \code{'membership'}, \code{'probability'}, or an
#'   integer value if \code{'none'}, the input data are already dissimilarities
#'   / distances; otherwise, which method to use for converting the original
#'   (similarity) matrix into a dissimiliarity / distance matrix that is then
#'   submitted to the MDS calculation
#' @param xfiInd an integer (default: 0) from which the original values are
#'   subtracted
#' @param clmSPP .
#' @param figCfg .
#' @param cfgBbl .
#' @param cfgInX .
#' @param cfgInY .
#' @param figShp .
#' @param figStr .
#' @param figRes .
#' @param figHst .
#' @param figWgh .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$genInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$tblCfg} \tab \tab \tab \tab \tab a table containing the fitted configurations \cr
#'   \code{results$figCfg} \tab \tab \tab \tab \tab a diagram showing the fitted configurations \cr
#'   \code{results$figShp} \tab \tab \tab \tab \tab TBA \cr
#'   \code{results$figStr} \tab \tab \tab \tab \tab TBA \cr
#'   \code{results$figRes} \tab \tab \tab \tab \tab TBA \cr
#'   \code{results$figHst} \tab \tab \tab \tab \tab TBA \cr
#'   \code{results$figWgh} \tab \tab \tab \tab \tab TBA \cr
#'   \code{results$addInf} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$ov_Cfg} \tab \tab \tab \tab \tab an output \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$tblCfg$asDF}
#'
#' \code{as.data.frame(results$tblCfg)}
#'
#' @export
mds <- function(
    data,
    mdeMDS = "Sym",
    varSym,
    nmeSym,
    lvlSym = "ordinal",
    dimSym = 2,
    xfmSym = "none",
    xfiSym = 0,
    varRaw,
    nmeRaw,
    lvlRaw = "ordinal",
    dimRaw = 2,
    dirRaw = "col",
    xfmRaw = "none",
    varInd,
    nmeInd,
    lvlInd = "ordinal",
    dimInd = 2,
    xfmInd = "none",
    xfiInd = 0,
    clmSPP = FALSE,
    figCfg = TRUE,
    cfgBbl = FALSE,
    cfgInX = FALSE,
    cfgInY = FALSE,
    figShp = FALSE,
    figStr = FALSE,
    figRes = FALSE,
    figHst = FALSE,
    figWgh = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("mds requires jmvcore to be installed (restart may be required)")

    if ( ! missing(varSym)) varSym <- jmvcore::resolveQuo(jmvcore::enquo(varSym))
    if ( ! missing(nmeSym)) nmeSym <- jmvcore::resolveQuo(jmvcore::enquo(nmeSym))
    if ( ! missing(varRaw)) varRaw <- jmvcore::resolveQuo(jmvcore::enquo(varRaw))
    if ( ! missing(nmeRaw)) nmeRaw <- jmvcore::resolveQuo(jmvcore::enquo(nmeRaw))
    if ( ! missing(varInd)) varInd <- jmvcore::resolveQuo(jmvcore::enquo(varInd))
    if ( ! missing(nmeInd)) nmeInd <- jmvcore::resolveQuo(jmvcore::enquo(nmeInd))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(varSym), varSym, NULL),
            `if`( ! missing(nmeSym), nmeSym, NULL),
            `if`( ! missing(varRaw), varRaw, NULL),
            `if`( ! missing(nmeRaw), nmeRaw, NULL),
            `if`( ! missing(varInd), varInd, NULL),
            `if`( ! missing(nmeInd), nmeInd, NULL))

    for (v in nmeSym) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in nmeRaw) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- mdsOptions$new(
        mdeMDS = mdeMDS,
        varSym = varSym,
        nmeSym = nmeSym,
        lvlSym = lvlSym,
        dimSym = dimSym,
        xfmSym = xfmSym,
        xfiSym = xfiSym,
        varRaw = varRaw,
        nmeRaw = nmeRaw,
        lvlRaw = lvlRaw,
        dimRaw = dimRaw,
        dirRaw = dirRaw,
        xfmRaw = xfmRaw,
        varInd = varInd,
        nmeInd = nmeInd,
        lvlInd = lvlInd,
        dimInd = dimInd,
        xfmInd = xfmInd,
        xfiInd = xfiInd,
        clmSPP = clmSPP,
        figCfg = figCfg,
        cfgBbl = cfgBbl,
        cfgInX = cfgInX,
        cfgInY = cfgInY,
        figShp = figShp,
        figStr = figStr,
        figRes = figRes,
        figHst = figHst,
        figWgh = figWgh)

    analysis <- mdsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

